site_name: wom.py

plugins:
  - search
  - autorefs
  - include-markdown
  - mkdocstrings:
      # custom_templates: docs/templates
      handlers:
        python:
          options:
            members_order: alphabetical
            docstring_style: google
            show_signature_annotations: true
            separate_signature: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - wom

theme:
  name: material
  # custom_dir: docs/overrides

  palette:
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  font:
    text: Noto Sans
    code: Noto Sans Mono

  logo: wom-logo.svg
  favicon: wom-logo.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github

extra:
  version:
    provider: mike
    default: stable

  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/wom.py/
      name: PyPI
    - icon: fontawesome/brands/github
      link: https://github.com/Jonxslays/wom.py/
      name: Source

copyright: Copyright &copy; 2023-present Jonxslays

repo_name: Jonxslays/wom.py
repo_url: https://github.com/Jonxslays/wom.py/
site_url: https://jonxslays.github.io/wom.py/

nav:
  - "index.md"
  - "Getting started":
      - "getting-started/installation.md"
      - "getting-started/client.md"
      - "getting-started/services.md"
      - "getting-started/result.md"
  - "Modules":
      - "reference/client.md"
      - "reference/enums.md"
      - "reference/errors.md"
      - "reference/models.md"
      - "reference/result.md"
      - "reference/routes.md"
      - "reference/serializer.md"
      - "reference/services.md"
  - "Migration guides":
      - "migrating/v1.md"
