name: Publish release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  pypi:
    name: Pypi release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: true

      - name: Run pre-release script
        id: prerelease
        run: ./scripts/pre-release.sh

      - name: Build and publish
        id: publish
        if: steps.prerelease.conclusion == 'success'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv build
          uv publish

      - name: Send release webhook
        if: steps.publish.conclusion == 'success'
        run: |
          VERSION=$(sed -rn 's/__version__: Final\[str\] = "(.*)"/\1/p' wom/__init__.py);

          curl -X POST ${{ secrets.WOM_DISCORD_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "username": "Automated Old Man",
              "avatar_url": "https://jonxslays.github.io/wom.py/dev/wom-logo.png",
              "embeds": [{
                "color": 3447003,
                "title": "wom.py v'$VERSION' has released to PyPI",
                "description": "**Upgrade with**:\n```pip install -U wom.py=='$VERSION'```\n- [Changelog](https://github.com/Jonxslays/wom.py/blob/master/CHANGELOG.md)\n- [Repository](https://github.com/Jonxslays/wom.py)\n- [Python Package Index](https://pypi.org/project/wom-py)"
              }]
            }'

  docs:
    name: Stable docs release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          python-version: "3.10"
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Build and deploy
        run: |
          git config --global user.name "Jonxslays"
          git config --global user.email "51417989+Jonxslays@users.noreply.github.com"
          git fetch origin gh-pages --depth=1
          uv run mike deploy --push --update-aliases $GITHUB_REF_NAME stable
